### ISSUE TITLE
Can't make it work in OJS 3

### ISSUE THREAD

**Issue by mukaanyes** [a-vodka/ojs_copernicus_export_plugin#1]
Can you please help make your plugin work in OJS 3. Or you can just respond to the post (https://forum.pkp.sfu.ca/t/how-to-create-xsd-format-for-index-copernicus/32846/17) in OJS forum and OJS staff can help.

Regards

**Comment by a-vodka** [comment]
Update is available
https://github.com/a-vodka/ojs_copernicus_export_plugin/blob/ojs3/downloads/copernicus3-0.0.2.tar.gz

**Comment by mukaanyes** [comment]
Thats very kind of you my friend. Best regards.

**Comment by mukaanyes** [comment]
I does not work in v 3.1.
to get it work with OJS 3.1, in line 121;
$url .= “/index.php/$jpath/article/view/” . $article->getId() . ‘/’ . $files->getFile()->getAssocId();
$url .= “/index.php/$jpath/article/view/” . $article->getId() . ‘/’ . $files->getFileId();

**Comment by surojitbera** [comment]
In OJS 3.1 instituteAffiliation not working.

**Comment by a-vodka** [comment]
> In OJS 3.1 instituteAffiliation not working.

Could you please provide more details?

**Comment by surojitbera** [comment]
Thanks for your reply @a-vodka. In OJS-3.1.1.2 author affiliation missing. Please see the Dropbox Link-[https://www.dropbox.com/s/w60e6ufzdptm5lw/author%20affiliation.png?dl=0](url) But I have change the affiliation code in CopernicusExportPlugin.inc.php. Please see the Dropbox link - [https://www.dropbox.com/s/hv48u04shmsfkcr/CopernicusExportPlugin.png?dl=0](url)
Now its working.. Please see final output Dropbox link- [https://www.dropbox.com/s/umzls4xj77u21rp/final%20XML.png?dl=0](url)

Thank you!
Surojit Bera

**Comment by a-vodka** [comment]
Ok, update is available

**Comment by jaliel123** [comment]
Can you help make your plugin work on OJS 2.4.5.0?.
